### ISSUE TITLE
Does the source code missing?

### ISSUE THREAD

**Issue by huyng12** [bayraktarulku/jitsi-activeSpeaker#1]
Hi team,

I am interested in your project, emoji-reaction specially. It seem missing some source code, isn't it? (I have never run it before). If it is, can you guys publish all the source code? I will very appreciate about that.

Thank you all, guys 🙏🏻

**Comment by bayraktarulku** [comment]
Hello, we've added the files and code blocks we've changed in the jitsi-meet repository.

**Comment by huyng12** [comment]
Oh, I see. I read the codebase then here is what I understand:

You make a fake command bar on top of the old one, then use IFrame API for do the things.
1. If it is a legacy command, call it by API (toggleAudio, toggleVideo, toggleChat...)
2. If it is an emoji, show a modal for choosing an emoji then set new avatar.

Please tell me if I am wrong. Thank you so much @bayraktarulku !

**Comment by bayraktarulku** [comment]
We did not work with the iframe API, but yes it can be set to it. But since we haven't tried it, I can't explain how to do it.
Or
After installing jitsi meet, you can apply the source code (changes we wrote in our document)

**Comment by huyng12** [comment]
Oh, I understand. Thank you so much @bayraktarulku for quick reply ❤️
